name: My first pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name:  checkout code
        uses: actions/checkout@v4 
      - name: Build image
        run: docker build -t tayad25/ciportfolios .

      - name: List Images
        run: docker images

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: echo hello
        run: echo "Hello World"
            
