name: My first pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: uptime
        run: uptime

      - name: number of processors
        run: nproc

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: echo hello
        run: echo "Hello World"
            
